# -*- coding: utf-8 -*-
"""news-apiV1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5CVCfxnQ-xPFxuycjgcISrKP5m-6g8Z
"""

!pip install newsapi-python

from google.colab import userdata
from newsapi import NewsApiClient
import json

try:
  api_key = userdata.get("NewsAPI")
except userdata.SecretNotFoundError:
  print("API anahtarı bulunamadı")
  raise SystemExit("API anahtarı gerekli.")

# NewsApiClient nesnesini başlat
newsapi = NewsApiClient(api_key=api_key)

# Türkiye'deki en popüler 5 haberi al
top_headlines = newsapi.get_top_headlines(country='tr', page_size=5)

# Haberleri ekrana yazdır
if all_articles['status'] == 'ok':
  print("\n--- 'Yapay Zeka' Konulu En Yeni 15 Haber ---")
  for i, article in enumerate(all_articles['articles']):
    print(f"{i+1}. Başlık: {article['title']}")
    print(f"Kaynak: {article['source']['name']}")
    print(f"Tarih: {article['publishedAt']}")
    print(f"URL: {article['url']}\n")
else:
  print("Konuyla ilgili haberler alınırken bir hata oluştu.")
  print(f"Hata detayı: {all_articles.get('message', 'Bilinmeyen hata')}")

# 'Yapay Zeka' konulu en yeni 15 haberi al
all_articles = newsapi.get_everything(q='yapay zeka',
                                      sort_by='publishedAt',
                                      page_size=15)

"""# Haberleri ekrana yazdır
if all_articles['status'] == 'ok':
  print("\n--- 'Yapay Zeka' Konulu En Yeni 15 Haber ---")
  for i, article in enumerate(all_articles['articles']):
    print(f"{i+1}. Başlık: {article['title']}")
    print(f"Kaynak: {article['source']['name']}")
    print(f"URL: {article['url']}\n")
else:
  print("Konuyla ilgili haberler alınırken bir hata oluştu.")
  print(f"Hata detayı: {all_articles.get('message', 'Bilinmeyen hata')}")"""

